import './globals.css'
import '../styles/_variables.scss'
import type { Metadata } from 'next'
import  { Inter, Nunito_Sans, Nunito,  }   from 'next/font/google'
import { ReduxProvider } from '@/redux/provider'

const nutino = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {  
  title: 'work room',
  description: 'Generated by create next app',
}

export default function RootLayout({ 
  children,
}: {
  children: React.ReactNode
}) { 
  return (
    <html lang="en">
      <body className={nutino.className}>
        <ReduxProvider>
          some layout styling and logic
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
