import './globals.css'
import type { Metadata } from 'next'
import  { Nunito_Sans }   from 'next/font/google'
import { ReduxProvider } from '@/src/redux/provider';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import { Toaster } from 'react-hot-toast';

const nutino = Nunito_Sans({ subsets: ['latin', 'cyrillic', 'latin-ext', 'vietnamese'] });
export const metadata: Metadata = {  
  title: 'work room',
  description: 'Generated by create next app',
}

export default function RootLayout({ 
  children,
}: {
  children: React.ReactNode
}) { 
  return (
    <html lang="en">
      <body className={nutino.className}>
        <ReduxProvider>
          {children}
          <Toaster/>
        </ReduxProvider>
      </body>
    </html>
  )
}
